version: '3'
services:
  gsa-dashboards:
    build: .
    image: minidfx/gsa-dashboards:v0.7.0
    environment:
      - SECRET_KEY_BASE=<secret-key>
      - KDRIVE_BRIDGE_HOST=<host>
      - BASIC_AUTH_USERNAME=<username>
      - BASIC_AUTH_PASSWORD=<password>
      - PLANNING_DOCUMENT_ID=<file-id>
      - ANNOTATION_LEFT_DOCUMENT_ID=<file-id>
      - ANNOTATION_RIGHT_DOCUMENT_ID=<file-id>
      - POOLING_INTERVAL=10000
      - TIMEZONE=<tz>
    ports:
      - 4000:4000
